name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Mono (for .NET Framework 4.7.2 support)
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0' # Schimbă cu versiunea ta de .NET

    - name: Restore dependencies
      run: dotnet restore Online-catalogue/Online-catalogue.csproj

    - name: Build project
      run: dotnet build Online-catalogue/Online-catalogue.csproj --configuration Release

    - name: Run tests
      run: dotnet test OnlineCatalogue.Tests/OnlineCatalogue.Tests.csproj --configuration Release
